import type { Generated } from "kysely";

export interface DatabaseSchema {
  workflow_prompts: {
    key: string;
    prompt: string;
    note: string | null;
    created_at: string;
    updated_at: string;
  };
  acp_kimi_session_owners: {
    session_id: string;
    operator_lark_id: string;
    title: string | null;
    ticket_base_id: string | null;
    ticket_table_id: string | null;
    ticket_record_id: string | null;
    ticket_number: string | null;
    runtime_host_name: string | null;
    kimi_work_dir: string | null;
    automation_action_key: string | null;
    execution_policy: string | null;
    skill_profile: string | null;
    skill_id: string | null;
    policy_version: string | null;
    thread_id: string | null;
    thread_snapshot_version: number | null;
    thread_context_synced_at: string | null;
    action_run_id: string | null;
    run_status: string | null;
    run_error_code: string | null;
    run_error_message: string | null;
    unverified_output: string | null;
    deleted_at: string | null;
    created_at: string;
    updated_at: string;
  };
  acp_kimi_sprint_session_refs: {
    session_id: string;
    operator_lark_id: string;
    project_key: string;
    sprint_id: string;
    context_hash: string;
    created_at: string;
    updated_at: string;
  };
  users: {
    id: string;
    status: string;
    lark_tenant_key: string | null;
    lark_id: string | null;
    lark_email: string | null;
    lark_name: string | null;
    lark_avatar_url: string | null;
    meegle_base_url: string | null;
    role: string | null;
    meegle_user_key: string | null;
    github_id: string | null;
    created_at: string;
    updated_at: string;
  };
  user_ssh_public_keys: {
    id: string;
    master_user_id: string;
    public_key: string;
    label: string | null;
    public_key_fingerprint: string | null;
    status: string;
    created_at: string;
    updated_at: string;
  };
  lark_contacts: {
    open_id: string;
    email: string | null;
    name: string | null;
    meegle_user_key: string | null;
    created_at: string;
    updated_at: string;
  };
  user_tokens: {
    master_user_id: string;
    provider: string;
    provider_tenant_key: string;
    external_user_key: string;
    base_url: string;
    plugin_token: string | null;
    plugin_token_expires_at: string | null;
    user_token: string;
    user_token_expires_at: string | null;
    refresh_token: string | null;
    refresh_token_expires_at: string | null;
    credential_status: string;
    last_auth_at: string;
    last_refresh_at: string | null;
    updated_at: string;
  };
  oauth_sessions: {
    state: string;
    provider: string;
    master_user_id: string | null;
    base_url: string;
    status: string;
    auth_code: string | null;
    external_user_key: string | null;
    error_code: string | null;
    expires_at: string;
    created_at: string;
    updated_at: string;
  };
  web_sessions: {
    session_token_hash: string;
    master_user_id: string;
    base_url: string;
    expires_at: string;
    created_at: string;
    updated_at: string;
    invalidated_at: string | null;
  };
  web_plugin_login_challenges: {
    challenge_id_hash: string;
    browser_proof_hash: string;
    status: string;
    master_user_id: string | null;
    base_url: string | null;
    expires_at: string;
    created_at: string;
    updated_at: string;
    consumed_at: string | null;
  };
  github_pr_review_runs: {
    action_run_id: string;
    master_user_id: string;
    operation: string;
    pr_url: string;
    status: string;
    comment_url: string | null;
    reviewed_files_json: string | null;
    feedback_count: number | null;
    feedback_record_ids_json: string | null;
    diff_truncated: boolean | null;
    error_code: string | null;
    error_message: string | null;
    created_at: string;
    started_at: string | null;
    completed_at: string | null;
    updated_at: string;
  };
  meegle_workitem_syncs: {
    project_key: string;
    project_name: string | null;
    work_item_type_key: string;
    work_item_id: string;
    work_item_key: string | null;
    title: string;
    work_item_type: string | null;
    status_key: string | null;
    status: string | null;
    sub_stage_key: string | null;
    sub_stage: string | null;
    sprint_id: string | null;
    sprint: string | null;
    version: string | null;
    system: string | null;
    bugs_json: string | null;
    assignee: string | null;
    priority: string | null;
    add_to_cycle_time: string | null;
    current_node_start_time: string | null;
    item_start_time: string | null;
    item_finish_time: string | null;
    created_at: Generated<string | null>;
    payload_json: string;
    source_updated_at: string | null;
    synced_at: string;
    last_seen_at: Generated<string | null>;
    stale: Generated<boolean>;
  };
  meegle_workitem_role_members: {
    project_key: string;
    work_item_type_key: string;
    work_item_id: string;
    role_key: string;
    role_name: string;
    member_key: string;
    member_name: string;
    role_order: number;
    member_order: number;
    synced_at: string;
  };
  meegle_workitem_sprint_memberships: {
    project_key: string;
    work_item_type_key: string;
    work_item_id: string;
    sprint_id: string;
    added_at: string;
    started_at: string | null;
    finished_at: string | null;
    removed_at: string | null;
    source: "historical_inferred" | "incremental_observed";
    created_at: string;
    updated_at: string;
  };
  meegle_sync_mappings: {
    project_key: string;
    work_item_type_key: string;
    mapping_kind: "workitem_type" | "status" | "sub_stage";
    source_key: string;
    display_value: string;
    synced_at: string;
  };
  github_pr_syncs: {
    owner: string;
    repo: string;
    pull_number: number;
    title: string;
    description: string | null;
    state: string;
    merged_at: string | null;
    html_url: string;
    author_login: string | null;
    merged_by_login: string | null;
    head_ref: string | null;
    base_ref: string | null;
    is_draft: boolean;
    meegle_ids: string;
    reviewers_json: string | null;
    labels_json: string | null;
    created_at: string | null;
    payload_json: string;
    source_updated_at: string | null;
    synced_at: string;
    last_seen_at: Generated<string | null>;
    stale: Generated<boolean>;
  };
  lark_base_ticket_syncs: {
    base_id: string;
    table_id: string;
    record_id: string;
    title: string;
    ticket_status: string | null;
    fields_json: string;
    shared_url: string | null;
    created_time: string | null;
    source_updated_at: string | null;
    synced_at: string;
    last_seen_at: Generated<string | null>;
    stale: Generated<boolean>;
    ticket_number: string | null;
    issue_type: string | null;
    requester: string | null;
    responsible: string | null;
    priority: string | null;
    detail_description: string | null;
    meegle_link: string | null;
    lark_message_link: string | null;
  };
  lark_ticket_thread_syncs: {
    base_id: string;
    table_id: string;
    record_id: string;
    message_link: string;
    thread_id: string;
    messages_json: string;
    prepared_messages_json: string | null;
    snapshot_version: Generated<number>;
    history_complete: Generated<boolean>;
    watermark_created_at: string | null;
    watermark_message_id: string | null;
    last_checked_at: string | null;
    last_successful_sync_at: string | null;
    last_full_reconciled_at: string | null;
    dirty: Generated<boolean>;
    frozen_at: string | null;
    frozen_status: string | null;
    last_error: string | null;
    created_at: string;
    updated_at: string;
  };
  support_analysis_runs: {
    id: string;
    action_run_id: string;
    source_name: string;
    status: string;
    taxonomy_version: string;
    rubric_version: string;
    created_at: string;
    updated_at: string;
  };
  support_thread_intent_segments: {
    id: string;
    analysis_run_id: string;
    base_id: string;
    table_id: string;
    record_id: string;
    snapshot_version: number;
    segment_key: string;
    redacted_summary: string | null;
    intent_json: string;
    evidence_message_ids_json: string;
    review_status: string;
    created_at: string;
    updated_at: string;
  };
  support_thread_results: {
    id: string;
    intent_segment_id: string;
    result_json: string;
    created_at: string;
    updated_at: string;
  };
  support_quality_reviews: {
    id: string;
    intent_segment_id: string;
    reviewer_kind: string;
    score_json: string;
    critical_issues_json: string;
    created_at: string;
    updated_at: string;
  };
  lark_ticket_eval_samples: {
    id: string;
    base_id: string;
    table_id: string;
    record_id: string;
    ticket_title: string;
    snapshot_version: number;
    ai_output_json: string;
    dataset_status: "draft" | "eval" | "badcase";
    manual_intent: string | null;
    expected_outcome: string | null;
    notes: string | null;
    failure_labels_json: string;
    created_at: string;
    updated_at: string;
  };
  support_ticket_reply_drafts: {
    id: string;
    base_id: string;
    table_id: string;
    record_id: string;
    session_id: string;
    operator_lark_id: string;
    draft_hash: string;
    status: string;
    sent_message_id: string | null;
    action_run_id: string | null;
    created_at: string;
    updated_at: string;
  };
  support_knowledge_documents: {
    id: string;
    source_kind: "controlled_document" | "approved_case";
    source_ref: string;
    title: string;
    redacted_summary: string | null;
    tags_json: string;
    approval_status: "approved" | "revoked";
    approved_by: string;
    approved_at: string;
    created_at: string;
    updated_at: string;
  };
  support_knowledge_chunks: {
    id: string;
    document_id: string;
    sequence: number;
    redacted_content: string;
    created_at: string;
    updated_at: string;
  };
  meegle_workitem_octo: {
    project_key: string;
    work_item_type_key: string;
    work_item_id: string;
    local_json: string;
    created_at: string | null;
    updated_at: string | null;
  };
  github_pr_octo: {
    owner: string;
    repo: string;
    pull_number: number;
    local_json: string;
    created_at: string | null;
    updated_at: string | null;
  };
  lark_base_ticket_octo: {
    base_id: string;
    table_id: string;
    record_id: string;
    shared_url: string | null;
    ticket_ai: string;
    local_json: string;
    created_at: string | null;
    updated_at: string | null;
  };
  platform_sync_checkpoints: {
    platform: "meegle" | "github" | "lark";
    scope_key: string;
    watermark_updated_at: string | null;
    watermark_tiebreaker: string | null;
    last_success_at: string | null;
    last_error: string | null;
    version: number;
    created_at: string;
    updated_at: string;
  };
  platform_sync_runs: {
    run_id: string;
    platform: "meegle" | "github" | "lark";
    scope_key: string;
    mode: "full" | "incremental" | "clean";
    clean_after_sync: boolean;
    started_at: string;
    completed_at: string | null;
    listed: number | null;
    skipped_inactive: number | null;
    synced: number | null;
    cleaned: number | null;
    stale: number | null;
    failed: boolean | null;
    error_message: string | null;
    status: "queued" | "running" | "succeeded" | "failed" | "skipped";
    trigger: "scheduled" | "manual" | "cli" | "retry";
    action_run_id: string;
    schedule_id: string | null;
    attempt: number;
    heartbeat_at: string | null;
    error_code: string | null;
  };
  platform_sync_schedules: {
    schedule_id: string;
    platform: "meegle" | "github" | "lark";
    scope_key: string;
    interval_seconds: number;
    enabled: boolean;
    managed_by: "config";
    master_user_id: string | null;
    target_json: string;
    next_run_at: string;
    retry_count: number;
    blocked_reason: string | null;
    last_enqueued_at: string | null;
    created_at: string;
    updated_at: string;
  };
  platform_sync_leases: {
    platform: "meegle" | "github" | "lark";
    scope_key: string;
    run_id: string;
    lease_token: string;
    lease_expires_at: string;
    heartbeat_at: string;
    created_at: string;
    updated_at: string;
  };
}
