export interface DatabaseSchema {
  workflow_prompts: {
    key: string;
    prompt: string;
    note: string | null;
    created_at: string;
    updated_at: string;
  };
  acp_kimi_session_owners: {
    session_id: string;
    operator_lark_id: string;
    title: string | null;
    deleted_at: string | null;
    created_at: string;
    updated_at: string;
  };
  users: {
    id: string;
    status: string;
    lark_tenant_key: string | null;
    lark_id: string | null;
    lark_email: string | null;
    lark_name: string | null;
    lark_avatar_url: string | null;
    meegle_base_url: string | null;
    role: string | null;
    meegle_user_key: string | null;
    github_id: string | null;
    created_at: string;
    updated_at: string;
  };
  lark_contacts: {
    open_id: string;
    email: string | null;
    name: string | null;
    meegle_user_key: string | null;
    created_at: string;
    updated_at: string;
  };
  user_tokens: {
    master_user_id: string;
    provider: string;
    provider_tenant_key: string;
    external_user_key: string;
    base_url: string;
    plugin_token: string | null;
    plugin_token_expires_at: string | null;
    user_token: string;
    user_token_expires_at: string | null;
    refresh_token: string | null;
    refresh_token_expires_at: string | null;
    credential_status: string;
    last_auth_at: string;
    last_refresh_at: string | null;
    updated_at: string;
  };
  oauth_sessions: {
    state: string;
    provider: string;
    master_user_id: string | null;
    base_url: string;
    status: string;
    auth_code: string | null;
    external_user_key: string | null;
    error_code: string | null;
    expires_at: string;
    created_at: string;
    updated_at: string;
  };
  web_sessions: {
    session_token_hash: string;
    master_user_id: string;
    base_url: string;
    expires_at: string;
    created_at: string;
    updated_at: string;
    invalidated_at: string | null;
  };
  web_plugin_login_challenges: {
    challenge_id_hash: string;
    browser_proof_hash: string;
    status: string;
    master_user_id: string | null;
    base_url: string | null;
    expires_at: string;
    created_at: string;
    updated_at: string;
    consumed_at: string | null;
  };
  github_pr_review_runs: {
    action_run_id: string;
    master_user_id: string;
    operation: string;
    pr_url: string;
    status: string;
    comment_url: string | null;
    reviewed_files_json: string | null;
    feedback_count: number | null;
    feedback_record_ids_json: string | null;
    diff_truncated: boolean | null;
    error_code: string | null;
    error_message: string | null;
    created_at: string;
    started_at: string | null;
    completed_at: string | null;
    updated_at: string;
  };
  meegle_workitem_syncs: {
    project_key: string;
    project_name: string | null;
    work_item_type_key: string;
    work_item_id: string;
    work_item_key: string | null;
    title: string;
    work_item_type: string | null;
    status_key: string | null;
    status: string | null;
    sub_stage_key: string | null;
    sub_stage: string | null;
    sprint: string | null;
    version: string | null;
    system: string | null;
    bugs_json: string | null;
    assignee: string | null;
    payload_json: string;
    source_updated_at: string | null;
    synced_at: string;
  };
  meegle_sync_mappings: {
    project_key: string;
    work_item_type_key: string;
    mapping_kind: "workitem_type" | "status" | "sub_stage";
    source_key: string;
    display_value: string;
    synced_at: string;
  };
  github_pr_syncs: {
    owner: string;
    repo: string;
    pull_number: number;
    title: string;
    description: string | null;
    state: string;
    merged_at: string | null;
    html_url: string;
    author_login: string | null;
    merged_by_login: string | null;
    head_ref: string | null;
    base_ref: string | null;
    is_draft: boolean;
    meegle_ids: string;
    reviewers_json: string | null;
    labels_json: string | null;
    created_at: string | null;
    payload_json: string;
    source_updated_at: string | null;
    synced_at: string;
  };
  lark_base_ticket_syncs: {
    base_id: string;
    table_id: string;
    record_id: string;
    title: string;
    ticket_status: string | null;
    fields_json: string;
    shared_url: string | null;
    created_time: string | null;
    source_updated_at: string | null;
    synced_at: string;
    ticket_number: string | null;
    issue_type: string | null;
    responsible: string | null;
    priority: string | null;
    detail_description: string | null;
    meegle_link: string | null;
    lark_message_link: string | null;
  };
  meegle_workitem_octo: {
    project_key: string;
    work_item_type_key: string;
    work_item_id: string;
    local_json: string;
    created_at: string | null;
    updated_at: string | null;
  };
  github_pr_octo: {
    owner: string;
    repo: string;
    pull_number: number;
    local_json: string;
    created_at: string | null;
    updated_at: string | null;
  };
  lark_base_ticket_octo: {
    base_id: string;
    table_id: string;
    record_id: string;
    local_json: string;
    created_at: string | null;
    updated_at: string | null;
  };
  platform_sync_checkpoints: {
    platform: "meegle" | "github" | "lark";
    scope_key: string;
    watermark_updated_at: string | null;
    watermark_tiebreaker: string | null;
    last_success_at: string | null;
    last_error: string | null;
    created_at: string;
    updated_at: string;
  };
}
