# .github/workflows/kimi-review.yml
name: Python Compile Check

on:
  pull_request:
    branches:
      - 'uat*'
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Compile Python files
        run: python .github/scripts/python_quality.py